### ISSUE TITLE
Dear admins a request 

### ISSUE THREAD

**Issue by ShivaBhattacharjee** [warlordsnet/animezia.com#13]
I've noticed that https://animezia.com/ is an exact replica of my project, Animetrix (animetrix.xyz). However, I understand the consequences of an open-source project, but I hope you respect my license terms and conditions. Could you please change the UI and refrain from using the same banner as mine, or at least add credits? Additionally, I'm not comfortable with you putting ads on my source code and earning money from it.

**Comment by animemandir** [comment]
Using it temporarily till mine is complete, will add credits.

**Comment by ShivaBhattacharjee** [comment]
> Using it temporarily till mine is complete, will add credits.

Please remove all the ads if you will be continuing to use my website source code & change the design its hurting my reputation as you are using the same logo and banner + the names are kinda similar too + there are ads respect the terms and conditions provided in my licence

**Comment by animemandir** [comment]
Not removing ads, will change logo and banner, animezia.com is running since 2020 idk why you thought yours is og.

**Comment by warlordsnet** [comment]
> > Using it temporarily till mine is complete, will add credits.
> 
> Please remove all the ads if you will be continuing to use my website source code & change the design its hurting my reputation as you are using the same logo and banner + the names are kinda similar too + there are ads respect the terms and conditions provided in my licence

Its piracy either way.

**Comment by ShivaBhattacharjee** [comment]
> > > Using it temporarily till mine is complete, will add credits.
> > 
> > Please remove all the ads if you will be continuing to use my website source code & change the design its hurting my reputation as you are using the same logo and banner + the names are kinda similar too + there are ads respect the terms and conditions provided in my licence
> 
> Its piracy either way. animezia has its own source code, first it used anikatsu then after few months we made our own, it ran for 2 yrs then again we made another ui, yours is being used for the time being, for a month or so, it wont be used for long.

Dont tryna act smart with me you are using my code and putting ads on it which i clearly restrict as the owner either use Someone else code or remove ads if you are using mine i clearly restrict anyone using AdSense to earn money from my work and yeah foss community isn't happy either for what you did either

**Comment by ShivaBhattacharjee** [comment]
> Not removing ads, will change logo and banner, animezia.com is running since 2020 idk why you thought yours is og.

You are using my code ? Man obviously I created it so yeah its og

**Comment by warlordsnet** [comment]
> > Not removing ads, will change logo and banner, animezia.com is running since 2020 idk why you thought yours is og.
> 
> You are using my code ? Man obviously I created it so yeah its og ps don't tryna act dumb or play weird games i dont mind doing a dmca complaint change the CODE or remove ADS and I mean it

Oh you mean it? DO IT. I'll wait.

**Comment by ShivaBhattacharjee** [comment]
> > > Not removing ads, will change logo and banner, animezia.com is running since 2020 idk why you thought yours is og.
> > 
> > You are using my code ? Man obviously I created it so yeah its og ps don't tryna act dumb or play weird games i dont mind doing a dmca complaint change the CODE or remove ADS and I mean it
> 
> Oh you mean it? DO IT. I'll wait.

Dont show your ego infront of me fucking copy cat give your twitter handle lets drag it there 
https://twitter.com/sh17va/status/1784507588417405340?t=yMxwnY9nw3KohJ8cn2LL7Q&s=19
Heres the thread for you get some balls and give your clarification here what are you? A fucking highschool kid? Idiots on GitHub fucking imbecile

**Comment by warlordsnet** [comment]
Moron tryna fight on twitter, I dont use it lol. Tf you gonna do with my pfp

**Comment by ShivaBhattacharjee** [comment]
> Moron tryna fight on twitter, I dont use it lol. Tf you gonna do with my pfp

Fight on twitter? Son of a bitch you stole my code and now you are trying to generate revenue who the fuck do you think you are idiot you term  yourself as web dev in reality you are nothing but a thief Thor and shasankk told me a lot of stuff about you too bitch change the code else there would be anikatsu season 2 fucking idiot

**Comment by anonthedev** [comment]
@warlordsnet at least have some respect for the open source community before you steal someone else's code and claim it to be your own. there's a fcking license in Shiv's repo that forbids you for using it for monetary purposes, have some shame.

**Comment by warlordsnet** [comment]
anikatsu season 2 ? you think it affected me ?😂 
> 
> Fight on twitter? Son of a bitch you stole my code and now you are trying to generate revenue who the fuck do you think you are idiot you term yourself as web dev in reality you are nothing but a thief Thor and shasankk told me a lot of stuff about you too bitch change the code else there would be anikatsu season 2 fucking idiot
 
What a retard, go jackoff somewhere else.

**Comment by elite-col** [comment]
> anikatsu season 2 ? you think it affected me ?😂
> 
> > Fight on twitter? Son of a bitch you stole my code and now you are trying to generate revenue who the fuck do you think you are idiot you term yourself as web dev in reality you are nothing but a thief Thor and shasankk told me a lot of stuff about you too bitch change the code else there would be anikatsu season 2 fucking idiot
> 
> What a retard, go jackoff somewhere else.

Wohh you guys doing great thing  huh ?

Fking moron thieves.

**Comment by ShivaBhattacharjee** [comment]
> anikatsu season 2 ? you think it affected me ?😂 
> > 
> > Fight on twitter? Son of a bitch you stole my code and now you are trying to generate revenue who the fuck do you think you are idiot you term yourself as web dev in reality you are nothing but a thief Thor and shasankk told me a lot of stuff about you too bitch change the code else there would be anikatsu season 2 fucking idiot
>  
> What a retard, go jackoff somewhere else. 

 You want some lawyers or what now? Read my licence dumb ass you cant use my code for monetization either disable adsense for a month or dont use my code

**Comment by warlordsnet** [comment]
> @warlordsnet at least have some respect for the open source community before you steal someone else's code and claim it to be your own. there's a fcking license in Shiv's repo that forbids you for using it for monetary purposes, have some shame.

oh no there's a license 😱, how did I miss that.

**Comment by ShivaBhattacharjee** [comment]
> > @warlordsnet at least have some respect for the open source community before you steal someone else's code and claim it to be your own. there's a fcking license in Shiv's repo that forbids you for using it for monetary purposes, have some shame.
> 
> oh no there's a license 😱, how did I miss that.

Cause you are autistic with no respect to open source community and an illiterate who cant read or write? Or just someone who cants read English maybe? Abide by it or I may have to start some campaign against you foss hates fools like you tho

**Comment by AYG45** [comment]
> Not removing ads, will change logo and banner, animezia.com is running since 2020 idk why you thought yours is og.

Lol Blud It's his idea his project he made it on his own ofcourse he'll think it's OG and Nobody gives a fck that your site running from 2020 all that matter is you steal it and now using it for your own profit.

**Comment by warlordsnet** [comment]
> Cause you are autistic with no respect to open source community and an illiterate who cant read or write? Or just someone who cant read English maybe? Abide by it or I may have to start some campaign against you foss hates fools like you tho

are you slow? this is piracy, you are doing it, and so am I, tf you gonna do about it?
btw I saw your tweets, you are getting really stressed over it lol. Also did you just pick up any git usernames you found on this repo ?

**Comment by ShivaBhattacharjee** [comment]
> 
> > Cause you are autistic with no respect to open source community and an illiterate who cant read or write? Or just someone who cant read English maybe? Abide by it or I may have to start some campaign against you foss hates fools like you tho
> 
> are you slow? this is piracy, you are doing it, and so am I, tf you gonna do about it?
> btw I saw your tweets, you are getting really stressed over it lol. Also did you just pick up any git usernames you found on this repo ? 

The web scrapper isn't mine and making this user interface took a lot of time and efforts and i have strict policy nobody can use my code for monetary purpose and you aren't respecting it? Thats the 1st principle of using open source software respect maintainer policies so yeah once again i urge you to please FUCKING disable adsense on my website code or just use some else code neither i am getting stressed it its the Foss people ps : I didnt find out the username and neither the user handle is mine dont act like a brat use your brain for once

**Comment by ShivaBhattacharjee** [comment]
> 
> > Cause you are autistic with no respect to open source community and an illiterate who cant read or write? Or just someone who cant read English maybe? Abide by it or I may have to start some campaign against you foss hates fools like you tho
> 
> are you slow? this is piracy, you are doing it, and so am I, tf you gonna do about it?
> btw I saw your tweets, you are getting really stressed over it lol. Also did you just pick up any git usernames you found on this repo ? 

And yeah I dont give a F about piracy its my website my work you dont get to earn revenue from it from free my software aren't designed to be used by the likes of you

**Comment by warlordsnet** [comment]
> And yeah I dont give a F about piracy its my website my work you dont get to earn revenue from it from free my software aren't designed to be used by the likes of you

idc.

**Comment by ShivaBhattacharjee** [comment]
> 
> > And yeah I dont give a F about piracy its my website my work you dont get to earn revenue from it from free my software aren't designed to be used by the likes of you
> 
> idc.

Then dont use my code or just admit you cant code mind it if i take down my api you cant do shit

**Comment by ShivaBhattacharjee** [comment]
> 
> > And yeah I dont give a F about piracy its my website my work you dont get to earn revenue from it from free my software aren't designed to be used by the likes of you
> 
> idc.

Thanks for disrespecting my work tho you and animemandir are gonna earn special mentions from now on

**Comment by warlordsnet** [comment]
> > > And yeah I dont give a F about piracy its my website my work you dont get to earn revenue from it from free my software aren't designed to be used by the likes of you
> > 
> > 
> > idc.
> 
> Thanks for disrespecting my work tho you and animemandir are gonna earn special mentions from now on

you got it wrong kid, I am just disrespecting the license, not the code.

**Comment by ShivaBhattacharjee** [comment]
> > > > And yeah I dont give a F about piracy its my website my work you dont get to earn revenue from it from free my software aren't designed to be used by the likes of you
> > > 
> > > 
> > > idc.
> > 
> > Thanks for disrespecting my work tho you and animemandir are gonna earn special mentions from now on
> 
> you got it wrong kid, I am just disrespecting the license, not the code.

Thats the same as disrespecting my work anyways what should i do report a dmca complaint or GitHub support devrels are asking me to make sure you regret what you did lets see tomorrow one thing for sure i will make you regret what you did

**Comment by animemandir** [comment]
> Thats the same as disrespecting my work anyways what should i do report a dmca complaint or GitHub support devrels are asking me to make sure you regret what you did lets see tomorrow one thing for sure i will make you regret what you did

regret is a very strong word. 😂
![image](https://media.tenor.com/rPs9SMzZ0lYAAAAM/how-you-felt-hero.gif)

**Comment by Sahil-Gulihar** [comment]
> row o
No wonder you have mandir in your username...
Bet your insta is full of Hindu Muslim Sigma Ligma shits xD

**Comment by shari003** [comment]
@warlordsnet uska address dedo koi vahi jaake thikane laga deta hu me

**Comment by animemandir** [comment]
> Give @warlordsnet address, will see what can I do

try and track him lol, tf u gonna do. He isnt even in india. I will give you his full address if you can even tell me which country he is in.

**Comment by ShivaBhattacharjee** [comment]
> > Give @warlordsnet address, will see what can I do
> 
> try and track him lol, tf u gonna do. He isnt even in india. I will give you his full address if you can even tell me which country he is in. 

Didn't you study in parul University btech 2025? 💀

**Comment by animemandir** [comment]
> 
> Didn't you study in parul University btech 2025? 💀

Where did you get this info from? If you have guts come to hostel A, tf you gonna do? didnt your cornyass say you will make me regret this?

**Comment by AYG45** [comment]
> > > Give @warlordsnet address, will see what can I do
> > 
> > try and track him lol, tf u gonna do. He isnt even in india. I will give you his full address if you can even tell me which country he is in. 
> 
> Didn't you study in parul University btech 2025? 💀

I can tell bro shit his pants

**Comment by ShivaBhattacharjee** [comment]
> 
> > 
> > Didn't you study in parul University btech 2025? 💀
> 
> Where did you get this info from? If you have guts come to hostel A, tf you gonna do? didnt your cornyass say you will make me regret this? 

😊 Dont worry i know a lot about you i dont give empty threats like you

**Comment by shari003** [comment]
@warlordsnet hostel A hai na, tu dekh ab

**Comment by warlordsnet** [comment]
> @warlordsnet hostel A hai na, tu dekh ab
![unnamed](https://github.com/warlordsnet/animezia.com/assets/96106468/b287cced-2655-488f-866e-8ea0d04199c5)

**Comment by warlordsnet** [comment]
> > ping me when you do something about it you soyfaced shilpit
> 
> Said by a mustard faced parul University student tier 3 kid who only knows how to copy

Its been a week 😊😊
