### ISSUE TITLE
Trending not working

### ISSUE THREAD

**Issue by KumaiIND** [warlordsnet/animezia.com#4]
It seems that the scrolling trending list isn't visible. Is there a way I can fix this, or is it still a work in progress?

**Comment by ROBBB111** [comment]
The homepage takes very long to load, is there a solution to this?

**Comment by KumaiIND** [comment]
Hello, ROBBB111! The speed of the website you have isn't controlled by the creator of animezia. The hosting service you are using may be slower than others, so you can always search online. As for my first comment on this issue, it seems to be fixed now, so I'll close this issue as soon as you read my message, or in 3 days from now. 

Cheers!
